using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraBars.Alerter;
using DevExpress.XtraEditors.Controls;
using JobLogging.JobloggingModel;

namespace JobLogging.Forms
{
    public partial class FrmStaff : DevExpress.XtraEditors.XtraForm
    {
        bool _isStaffsChange;
        public FrmStaff()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            //GlobalParams.modelContainer.Staffs.Load();
            //GlobalParams.modelContainer.Roles.Load();roleBindingSource.DataSource = GlobalParams.modelContainer.Roles;

            roleBindingSource.DataSource = GlobalParams.modelContainer.Roles;
            // This line of code is generated by Data Source Configuration Wizard
            usersBindingSource.DataSource = GlobalParams.modelContainer.Users;
        }
        private void FrmStaff_Load(object sender, System.EventArgs e)
        {
           
        }

        private void FrmStaff_FormClosing(object sender, System.Windows.Forms.FormClosingEventArgs e)
        {

            //if (GlobalParams.modelContainer.Staffs.Local.
            //    .GetObjectStateEntries(System.Data.EntityState.Added | System.Data.EntityState.Modified)
            //    .Any())
            if (GlobalParams.modelContainer.ObjectStateManager.GetObjectStateEntries(System.Data.EntityState.Added | System.Data.EntityState.Deleted | System.Data.EntityState.Modified).Any())
            {
                _isStaffsChange = true;
            }
            if (_isStaffsChange)
            {
                var dialogResult = MessageBox.Show("有未保存的数据有变更，选是立即保存并退出，选否放弃修改并退出！", "警告",
                                                   MessageBoxButtons.YesNoCancel);
                if (dialogResult == DialogResult.Yes)
                    if (this.Validate(false))
                    {
                        GlobalParams.modelContainer.SaveChanges();
                    }
                    
                if (dialogResult == DialogResult.No)
                {
                    GlobalParams.modelContainer.Refresh(System.Data.Objects.RefreshMode.StoreWins,
                                                        GlobalParams.modelContainer.Users);
                    GlobalParams.modelContainer.AcceptAllChanges();}


                if (dialogResult == DialogResult.Cancel)
                    e.Cancel = true;
            }
        }

        private void gridView1_ValidateRow(object sender, DevExpress.XtraGrid.Views.Base.ValidateRowEventArgs e)
        {
            var name = gridView1.GetRowCellValue(e.RowHandle, "Name");

            if (name == null)
            {
                e.ErrorText = "姓名不允许为空!";
                e.Valid = false;
            }
            else
            {
                var strName = name.ToString();
                var id = Convert.ToInt32(gridView1.GetRowCellValue(e.RowHandle, "ID"));
                if (GlobalParams.modelContainer.Users.Count(t => t.Name == strName && t.ID != id) > 0)
                {
                    e.ErrorText = "该姓名已存在,请更正!";
                    e.Valid = false;
                }
            }

        }

        private void gridView1_ValidatingEditor(object sender, BaseContainerValidateEditorEventArgs e)
        {
            if (gridView1.FocusedColumn.FieldName == "Name")
            {
                var name = e.Value.ToString();
                if (string.IsNullOrWhiteSpace(name))
                {
                    e.ErrorText = "姓名不允许为空!";
                    e.Valid = false;
                }
                else
                {
                    var id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                    if (GlobalParams.modelContainer.Users.Count(t => t.Name == name && t.ID != id) > 0)
                    {
                        e.ErrorText = "该姓名已存在,请更正!";
                        e.Valid = false;
                    }
                }
            }
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            GlobalParams.modelContainer.SaveChanges();
            var info = new AlertInfo("提示：", "修改已保存！",sharedImageCollection1.ImageSource.Images[0]);
            alertControl1.Show(this, info);
        }
    }
}
